Allow trailing commas in grouped use declarations in PHP 7.2+
pdepend/pdepend pull request #520
Opened 2021-03-25 19:00 UTC by JKapitein

Type: bugfix
Issue: #519 
Breaking change: no

Feels like a lot of duplication, but couldn't really figure out a way to insert the early break on T_CURLY_BRACE_CLOSE into the 7.0 parser. I'm also struggling to run the entire testsuite locally, so I don't know what will happen once the GitHub actions run.

2021-03-25 20:11 UTC, AJenbo commented on src/test/php/PDepend/Source/Language/PHP/PHPParserVersion72Test.php
> +        $this->assertNotNull($namespaces);
I'm a bit unsure what `parseCodeResourceForTest` will return, but maybe better to assert that it's an instance of `ASTNamespace` rather than not `null`?

2021-03-25 20:12 UTC, AJenbo commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
> +            if (Tokens::T_CURLY_BRACE_CLOSE == $this->tokenizer->peek()) {
```suggestion
            if (Tokens::T_CURLY_BRACE_CLOSE === $this->tokenizer->peek()) {
```

2021-03-25 20:12 UTC, AJenbo commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
> +            if (Tokens::T_COMMA != $this->tokenizer->peek()) {
```suggestion
            if (Tokens::T_COMMA !== $this->tokenizer->peek()) {
```

2021-03-25 20:13 UTC, AJenbo requested changes
Looks fine, with a few minor comments.

2021-03-25 20:17 UTC, JKapitein commented on src/test/php/PDepend/Source/Language/PHP/PHPParserVersion72Test.php
> +        $this->assertNotNull($namespaces);
I'm uncertain, this was copied from the 7.0 test but adds support for trailing commas

2021-03-25 20:27 UTC, JKapitein commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
> +            if (Tokens::T_CURLY_BRACE_CLOSE == $this->tokenizer->peek()) {
The 7.0 code also didn't use strict comparison, I assumed there was a reason. I'll defer to the authors/members as to whether or not strict comparison is wanted here,

2021-03-25 20:58 UTC, kylekatarnls commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
> +            if (Tokens::T_CURLY_BRACE_CLOSE == $this->tokenizer->peek()) {
Indeed I checked the project, we have few other `==` one thing for sure, it's a mistake when comparing `peek()` to a token constant. Those one can be safely fixed.

2021-03-25 21:19 UTC, kylekatarnls commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
> +    }
I guess we could try to share a bit more code between PHPParserVersion72.php and PHPParserVersion70.php.

But the approach is fine.

2021-03-25 21:25 UTC, AJenbo submitted a review, later dismissed

2021-03-25 21:34 UTC, JKapitein commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
> +    }
Feels like it would lead to weird inheritance structures because of the while(true) loop. That said I'm open to suggestions.

2021-03-30 16:45 UTC, JKapitein commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
> +    }
@kylekatarnls The cleanest thing I can think of is adding a method in the PHPParserVersion70 on that point which breaks the `do` on returning true. It always returns false in PHPParserVersion70, but can return true in PHPParserVersion72. I'm reluctant to make it like that because the inheritance would go the wrong way, flowing up instead of down. Either that or split it into multiple submethods that the PHPParserVersion72 can override, but with me not being able to run the full testsuite locally that would just lead to me doing a lot of trial and error on the repository here where the actions run.

Thoughts?

2021-04-11 15:31 UTC, kylekatarnls commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion72.php
> +    }
I implemented it this way. I think it's fine regarding the very little quantity of code Version70 need to embed to support it vs. the big duplicate chunk doing the other way. Plus: it gives us an explicit description of changes over versions:
- PHP 7.0 add user declaration group, but allowUseGroupDeclarationTrailingComma = false
- PHP 7.2 allowUseGroupDeclarationTrailingComma = true

Due to the big amount of inheritance (each version inherit the previous one) it's bigger concerne in my opinion to keep each sub-class as small as possible, descriptive in the changes they introduced from the previous versions and to create sub-methods to avoid accidental override of a too big chunk so the next one that will fix something in the `use` parser won't fix PHP 7.2 missing the PHP 7.0 version or the contrary.

2021-04-11 15:34 UTC, kylekatarnls approved these changes

2021-04-11 15:35 UTC, AJenbo approved these changes

2021-04-11 15:46 UTC, merged

2021-04-11 19:47 UTC, JKapitein commented
Thank you @kylekatarnls !