PHP 8.1 support in-initializers
pdepend/pdepend pull request #598
Opened 2022-04-09 20:36 UTC by kylekatarnls

Type: feature
Issue: #556
Breaking change: no

2022-04-09 22:39 UTC, AJenbo commented
Nice work, this is one of the best features of 8.1 :)

I'll try and review this either this weekend or the coming week.

If you need inspiration for what to work on next Enum support would be much appreciated :sweat_smile:

2022-04-11 20:19 UTC, ravage84 requested changes

2022-04-11 20:19 UTC, ravage84 commented on src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
> +     * declaration.
```suggestion
     * Parse a default value after a parameter, static variable or constant declaration.
```

2022-04-11 20:19 UTC, ravage84 commented on src/test/php/PDepend/Source/Language/PHP/Features/PHP81/InInitializersTest.php
> + * @copyright 2008-2017 Manuel Pichler. All rights reserved.
Just a side note: We shouldn't attribute this to him anymore, as he actively left the project and he does not in any way do an want to contriibute to its new code.

2022-04-11 20:19 UTC, ravage84 commented on src/test/resources/files/Source/Language/PHP/Features/PHP81/InInitializers/testInInitializers.php
> +        public Bar $bar = new Bar,
I think it wouldn't hurt if we extended this example/test to two parameters, the second with a less open visiblity, may be.
May be even a third with no value.

2022-04-13 15:56 UTC, kylekatarnls commented on src/test/php/PDepend/Source/Language/PHP/Features/PHP81/InInitializersTest.php
> + * @copyright 2008-2017 Manuel Pichler. All rights reserved.
```suggestion
```

2022-08-14 20:08 UTC, AJenbo submitted a review, later dismissed

2022-08-15 14:27 UTC, kylekatarnls commented on src/test/resources/files/Source/Language/PHP/Features/PHP81/InInitializers/testInInitializers.php
> +        public Bar $bar = new Bar,
Done.

2022-08-15 20:40 UTC, tvbeek approved these changes

2022-08-15 20:40 UTC, merged