Add lazy configuration for Symfony
pdepend/pdepend pull request #699
Opened 2023-12-06 12:59 UTC by kylekatarnls

Type: bugfix
Issue: Fix #695
Breaking change: no

2023-12-06 13:23 UTC, AJenbo reviewed
I think rather then checking the parent for a return type we can simply do it if it's php 7+ since it's always valid to narrow the return. Other then that I like this approach.

2023-12-06 13:30 UTC, kylekatarnls commented
> I think rather then checking the parent for a return type we can simply do it if it's php 7+ since it's always valid to narrow the return. Other then that I like this approach.

No, you can perfectly run PHP 8.3 and install Symfony 5 if you like. PHP level is irrelevant there.

2023-12-06 13:33 UTC, AJenbo commented
> > I think rather then checking the parent for a return type we can simply do it if it's php 7+ since it's always valid to narrow the return. Other then that I like this approach.
> 
> No, you can perfectly run PHP 8.3 and install Symfony 5 if you like. PHP level is irrelevant there.

But, you can perfectly use Symfony 5 and still add return types. Symfony version is irrelevant here.

2023-12-06 13:57 UTC, kylekatarnls commented
> But, you can perfectly use Symfony 5 and still add return types. Symfony version is irrelevant here.

"you" will need to be prevised in this story.

Because if PDepend add return types on a public method on a non-final method, it's a breaking change, so it might break whoever build on the top of it.

If we base on PHP level, we actually narrow typing when PHP >= 7 and Symfony < 7 => BC, and 3 mix to support.

If we simply strictly align our definition to current Symfony declaration, we keep on 2 mix to support and don't create any new divergence that can break in dependent projects (including user world but also PHPMD).

2023-12-06 14:07 UTC, AJenbo commented
> Because if PDepend add return types on a public method on a non-final class, it's a breaking change, so it might break whoever build on the top of it.

That's fair enough, I did not see this as an issue for classes we extend. But yeah if we are that strict about it your solution ins the better one.

2023-12-07 18:35 UTC, AJenbo approved these changes

2023-12-07 18:41 UTC, kylekatarnls commented
For the record, here is the demonstration that will also solve the issue in PHPMD:
https://github.com/phpmd/phpmd/pull/1049

2023-12-07 18:43 UTC, ravage84 commented on src/test/composer.json
Why aren't we using PHIVE for that, instead?

2023-12-07 18:45 UTC, kylekatarnls commented on src/test/composer.json
Because we use an old PHPUnit version and modify it to make it run with PHP >= 8.

So really not convenient to download phar, then edit and rebuild a new phar, resign and run it.

It will be possible when we'll drop old version and upgrade to a newer version of PHPUnit that support PHP up to 8.3 out of the box.

2023-12-07 18:59 UTC, AJenbo commented on src/test/composer.json
Will we ever?

2023-12-07 19:02 UTC, ravage84 commented on composer.json
> -        "phpunit/phpunit": "^4.8.36|^5.7.27",
Doesn't that mean ``composer test`` doesn't work anymore?

Plus, doesn't it mean PHPUnit isn't setup locally when one sets up pdepend as a project locally?

2023-12-07 19:08 UTC, ravage84 requested changes

2023-12-07 19:08 UTC, ravage84 commented on src/main/php/Lazy/PDepend/DependencyInjection/Configuration.strong.php
> +
```suggestion

```

2023-12-07 19:08 UTC, ravage84 commented on src/main/php/Lazy/PDepend/DependencyInjection/Configuration.weak.php
> +
```suggestion

```

2023-12-07 19:08 UTC, ravage84 commented on src/test/composer.json
> +    "name": "pdepend/pdepend-tester",
```suggestion
    "name": "pdepend/pdepend-tester",
    "description": "Test-related dependencies for pdepend/pdepend",
```

2023-12-07 19:08 UTC, ravage84 commented on src/test/symfony-version.php
> +<?php
Can we add a short description what this file provides?

2023-12-08 01:18 UTC, AJenbo approved these changes

2023-12-08 08:59 UTC, AJenbo approved these changes

2023-12-08 23:24 UTC, AJenbo commented on src/main/php/Lazy/PDepend/DependencyInjection/Configuration.strong.php
> +// <AbstractConfiguration>
I don't get it?

2023-12-08 23:32 UTC, kylekatarnls commented on src/main/php/Lazy/PDepend/DependencyInjection/Configuration.strong.php
> +// <AbstractConfiguration>
The one on the `.strong` file is not needed indeed, just if we want to switch later the PHP+Symfony version for phar building later. But I guess we'll just drop all together the old.

2023-12-08 23:33 UTC, kylekatarnls commented on src/main/php/Lazy/PDepend/DependencyInjection/Configuration.strong.php
> +// <AbstractConfiguration>
The idea behind `<AbstractConfiguration>...</AbstractConfiguration>`  is to be extracted and put in `src/main/php/PDepend/DependencyInjection/Configuration.php` when building phar.

2023-12-10 03:02 UTC, AJenbo approved these changes

2023-12-10 17:01 UTC, merged