Resolve a few PHPstan level 7 issues
pdepend/pdepend pull request #711
Opened 2024-02-06 07:25 UTC by AJenbo

Type: bugfix|documentation  
Breaking change: no

Gets us from 68 to 55 renaming issues at level 7. This is mainly done by checking for invalid configurations and adjusting a few signatures.

2024-02-06 08:28 UTC, kylekatarnls commented on src/main/php/PDepend/Report/Overview/Pyramid.php
> +        $templatePath = dirname(__FILE__) . '/pyramid.svg';
```suggestion
        $templatePath = __DIR__ . '/pyramid.svg';
```
Twice the same modification, this sounds like an opportunity to dedupe the SVG loading. A `private loadSvgFile()` would be nice.

2024-02-06 08:31 UTC, kylekatarnls commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
> +        if (isset($image, $subFragments) && $image) {
I think we have some `$image` being `""`

2024-02-06 08:33 UTC, kylekatarnls commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
> +        if (isset($image, $subFragments) && $image) {
```suggestion
        if (isset($image, $subFragments) && $image !== false) {
```

2024-02-06 08:34 UTC, kylekatarnls requested changes
All good aside the open comments

2024-02-06 09:17 UTC, AJenbo commented on src/main/php/PDepend/Report/Jdepend/Chart.php
> +        $templatePath = dirname(__FILE__) . '/chart.svg';
Oh wow you are right, I thought it wasn't added before 5.4 so I have been leaving them alone, let me just change that (hopefully this won't escalate)

2024-02-06 09:18 UTC, AJenbo commented on src/main/php/PDepend/Report/Overview/Pyramid.php
> +        $templatePath = dirname(__FILE__) . '/pyramid.svg';
They are not in the same file so private at the very least is not an option. Any chance we can take this opportunity another time?

2024-02-06 09:22 UTC, AJenbo commented on src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php
> +        if (isset($image, $subFragments) && $image) {
Done

2024-02-06 09:34 UTC, kylekatarnls submitted a review, later dismissed

2024-02-06 09:39 UTC, kylekatarnls commented on src/test/resources/files/bugs/030/testCorrectClassTokensAreSet.php
> +        $sourceFile = __DIR__ . '/my/test/file.php';
```suggestion
        $sourceFile = dirname(__FILE__) . '/my/test/file.php';
```

2024-02-06 09:40 UTC, kylekatarnls commented on src/test/resources/files/bugs/030/testCorrectClassTokensAreSet.php
> +        $sourceFile = __DIR__ . '/my/test/file.php';
It's a test file example and `testCorrectClassTokensAreSet` check token list from it, so we should let it as is.

2024-02-06 09:40 UTC, kylekatarnls approved these changes

2024-02-06 09:41 UTC, AJenbo commented on src/test/resources/files/bugs/030/testCorrectClassTokensAreSet.php
> +        $sourceFile = __DIR__ . '/my/test/file.php';
Thanks

2024-02-10 14:06 UTC, merged

2024-02-10 17:01 UTC, AJenbo commented
@kylekatarnls Hm I had expected the Coverage / PHP 8.3 to pass once merged but it looks like it's still complaining about the config, any ideas?

2024-02-10 20:19 UTC, kylekatarnls commented
At least the generate-phar pass once merged.

On this particular job the script fixing compatibility didn't find the files:
![image](https://github.com/pdepend/pdepend/assets/5966783/4f05c5fd-ff6b-4f33-a11f-56273237e74c)

2024-02-10 20:21 UTC, kylekatarnls commented
Ah oops, found. What I did to split main and test dependencies is not applied on the coverage build.

2024-02-10 21:13 UTC, kylekatarnls commented
Fixed #715