Hndle null cases
pdepend/pdepend pull request #807
Opened 2024-05-08 09:05 UTC by AJenbo

Type: refactoring / documentation update
Breaking change: no

2024-05-12 23:39 UTC, ravage84 requested changes

2024-05-12 23:39 UTC, ravage84 commented on src/main/php/PDepend/Report/Jdepend/Chart.php
> +     * @throws RuntimeException
```suggestion
     * @throws RuntimeException If a layer element is missing.
```

Would be nice to have some explanation.
Otherwise, we have to have discuss about useless doc blocks again. 😏 

Applies to all of these cases.

2024-05-12 23:39 UTC, ravage84 commented on src/main/php/PDepend/Report/Jdepend/Chart.php
> +            throw new RuntimeException('Missing jdepend.layer element');
There is a lot of branching code added of which none seems to be covered.

Either these cases are ultra rare or we simply haven't good coverage on them, yet.

It would be sensible to add test coverage on them, then.

2024-05-12 23:39 UTC, ravage84 commented on src/main/php/PDepend/Report/Jdepend/Xml.php
> +use RuntimeException;
Using a custom exception which could be a child of that one would be more expressive.

2024-05-12 23:39 UTC, ravage84 commented on src/main/php/PDepend/Source/AST/ASTInterface.php
> +        $this->context?->registerInterface($this);
Do we want it to not fail if it's null?

2024-05-12 23:39 UTC, ravage84 commented on src/main/php/PDepend/Source/AST/ASTTrait.php
> +        $this->context?->registerTrait($this);
Do we want it to not fail if it's null?

2024-05-12 23:39 UTC, ravage84 commented on src/main/php/PDepend/Source/AST/AbstractASTType.php
> +            ?->type('tokens')
Should the question mark be on the new line?

I'm asking in hinsight of code style.

For me, this operator is part of the line above, having consequences for this one.

2024-05-12 23:39 UTC, ravage84 commented on src/main/php/PDepend/Source/Language/PHP/PHPParserGeneric.php
> +                    $this->tokenizer->getSourceFile() ?? 'unknown'
Just a side note: 
In the future, I'd like to get rid of magic literals like this one.

2024-05-12 23:44 UTC, AJenbo commented on src/main/php/PDepend/Metrics/Analyzer/ClassDependencyAnalyzer.php
> +        }
I don't think we can do it in getParent() since it's sometimes used in a loop, but getParentOrFail() sound good to me.

2024-05-12 23:49 UTC, AJenbo commented on src/main/php/PDepend/Report/Jdepend/Chart.php
> +            throw new RuntimeException('Missing jdepend.layer element');
most of them are very rare, often they would only show up after some bad refactor that doesn't use the object as intended. Or someone using PDepend incorrectly in there external project.

I'll split them in to there own PR so they do not hold back the rest of the PR.

2024-05-12 23:51 UTC, AJenbo commented on src/main/php/PDepend/Report/Jdepend/Xml.php
> +use RuntimeException;
I agree, though I don't see a pattern for how this should be done, instead using PHP's exceptions seems to be the norm for the project. Changing this might be a refactor and planing point in it self, maybe someone could start a debate about it :)

2024-05-12 23:53 UTC, AJenbo commented on src/main/php/PDepend/Source/AST/ASTInterface.php
> +        $this->context?->registerInterface($this);
It was my best guess, but it was hard to judge.

2024-05-12 23:56 UTC, AJenbo commented on src/main/php/PDepend/Source/AST/AbstractASTType.php
> +            ?->type('tokens')
https://wiki.php.net/rfc/nullsafe_operator refers to `?->` as an operator. I don't think we should split it up.

2024-05-13 20:55 UTC, AJenbo commented on src/main/php/PDepend/Source/AST/ASTTrait.php
> +        $this->context?->registerTrait($this);
Handled via https://github.com/pdepend/pdepend/pull/814

2024-05-13 20:56 UTC, AJenbo commented on src/main/php/PDepend/Source/AST/ASTInterface.php
> +        $this->context?->registerInterface($this);
Handled via https://github.com/pdepend/pdepend/pull/814

2024-05-13 21:23 UTC, AJenbo commented on src/main/php/PDepend/Report/Jdepend/Chart.php
> +            throw new RuntimeException('Missing jdepend.layer element');
Moved to https://github.com/pdepend/pdepend/pull/816

2024-05-13 21:23 UTC, AJenbo commented on src/main/php/PDepend/Report/Jdepend/Chart.php
> +     * @throws RuntimeException
See https://github.com/pdepend/pdepend/pull/816

2024-05-13 21:24 UTC, AJenbo commented on src/main/php/PDepend/Metrics/Analyzer/ClassDependencyAnalyzer.php
> +        }
To not block the other changes in this PR I have moved the exceptions to https://github.com/pdepend/pdepend/pull/816

2024-05-14 15:54 UTC, ravage84 approved these changes

2024-05-14 15:54 UTC, merged

2024-05-14 16:05 UTC, AJenbo commented
Thanks, we are making big steps now :)