Fixed error when accessing constant array item, issue #713
pdepend/pdepend pull request #808
Opened 2024-05-09 12:57 UTC by rinu

Type: bugfix
Issue: #713 
Breaking change: no

2024-05-09 14:03 UTC, AJenbo commented
it would be good to have a test case for this

2024-05-10 06:42 UTC, rinu commented
It would be helpful if the project had documentation for contributors. Perhaps there's something hidden, documentation links on https://pdepend.org/ are broken. I'm looking for information like how to run tests when the project uses a phpunit version that is 6 years old and doesn't run on any current PHP version.

2024-05-10 09:46 UTC, AJenbo submitted a review, later dismissed

2024-05-10 09:47 UTC, AJenbo commented
thanks :)

2024-05-12 22:43 UTC, ravage84 requested changes

2024-05-12 22:43 UTC, ravage84 commented on src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php
> +        if ($this->tokenizer->peek() === Tokens::T_SQUARED_BRACKET_OPEN) {
I think this change should be reflected in the method doc block's code examples.

2024-05-12 22:43 UTC, ravage84 commented on src/test/php/PDepend/Bugs/ParserBug713Test.php
> + * @covers \stdClass
That doesn't make much sense. Let's better state the actual coverage:

```suggestion
 * @covers \PDepend\Source\Language\PHP\AbstractPHPParser::parseIssetExpression
```

2024-05-12 22:43 UTC, ravage84 commented on src/test/resources/files/bugs/713/testConstantArrayIndexIsset.php
> +if (isset(FOO['foo'])) {}
Does it work for two, three or more levels, too?

```suggestion
if (isset(FOO['foo'])) {}

if (isset(FOO['foo']['bar'])) {}

if (isset(FOO['foo']['bar']['baz'])) {}
```

2024-05-12 22:43 UTC, ravage84 commented on src/test/php/PDepend/Bugs/ParserBug713Test.php
> +        $cache   = new MemoryCacheDriver();
Right now, this test doesn't assert anything, if I see correctly. In future PHPUnit ersions, which we use for PHP Depend 3.x , this will be detected as risky test.

Can we assert anything sensible?

2024-05-13 08:05 UTC, rinu commented on src/test/php/PDepend/Bugs/ParserBug713Test.php
> +        $cache   = new MemoryCacheDriver();
There's nothing to assert really. The idea is to expect no exceptions. Added `@doesNotPerformAssertions`.

2024-05-13 08:06 UTC, rinu commented on src/test/resources/files/bugs/713/testConstantArrayIndexIsset.php
> +if (isset(FOO['foo'])) {}
Did not, fixed.

2024-05-13 08:24 UTC, ravage84 approved these changes

2024-05-13 08:25 UTC, ravage84 commented
Thanks a lot for the fast folow-up, @rinu

2024-05-13 08:34 UTC, merged